apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: kustomize-env-plugin
spec:
  version: v1.0
  discover:
    find:
      command: ["sh", "-c", "find . -name kustomization.yaml"]
  generate:
    command: ["render-kustomize.sh"]