apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: kustomize-env-plugin
spec:
  init:
    command: [sh]
    args: [-c, 'echo "Initializing kustomize-env-plugin"']
  discover:
    find:
      command: ["sh", "-c", "set -e; find . -maxdepth 1 -iname 'kustomization.y*ml' | head -n 1"]
  generate:
    command: ["render-kustomize.sh"]