apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: kustomize-env-plugin
spec:
  version: v1.0
  discover:
    find:
      command: ["sh", "-c", "cd $ARGOCD_APP_PATH && find . -maxdepth 1 -name kustomization.yaml"]
  generate:
    command: ["sh", "-c", "cd $ARGOCD_APP_PATH && render-kustomize.sh"]