apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: kustomize-env-plugin
spec:
  version: v1.0
  discover:
    find:
      command: ["sh", "-c", "set -e; find $ARGOCD_APP_SOURCE_PATH -name kustomization.yaml"]
  generate:
    command: ["sh", "-c", "set -e; cd $ARGOCD_APP_SOURCE_PATH && render-kustomize.sh"]